language: ruby

before_install: mkdir -p output

install:
  - bundle config --local github.https true
  - bundle --path=.bundle/gems --binstubs=.bundle/.bin
  - cp common/stylesheets/asciidoctor.css output/asciidoctor.css

script:
  - bundle exec asciidoctor -D output README.adoc -a linkcss -a stylesheet=asciidoctor.css

after_success:      
  - cd output
  - cp -R ../images .
  - mv README.html index.html
  - git init
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "{GH_USER_EMAIL}"
  - git add .
  - git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1
